public class exception4 {
    public static void main(String args[]){
        //try{
           // System.out.println(10/0);
            System.out.println("try");
            throw new ArithmeticException("by zero");
            // try{
            //     System.out.println(10/0);
            // }
            // catch(Exception e){
            //     System.out.println(10/2);

            // }
           // System.out.println(10/0);
           // System.exit(9);
        
        }
        
    //     catch(Exception e){
    //         System.out.println("catch");
    //         System.out.println(e);

    //     }
    //     finally{
    //         System.out.println("finally");
    //     }
        
    //     System.out.println("normal flow");
    // }   
}
